version: '3'

services:

  ppfchecklist:
    image: ppfchecklist
    container_name: ppfchecklist
    restart: unless-stopped
    ports:
      - 5000:80
    volumes:
      - ./.env.sample:/usr/src/app/.env
      - ./client_secrets.json.sample:/usr/src/app/client_secrets.json
      - ./list.db.sample:/usr/src/app/list.db
      - ./tables.json.sample:/usr/src/app/tables.json
